### ISSUE TITLE
UI effects for Dialogue

### ISSUE THREAD

**Issue by chadleytan** [FinnbarrOC/EspionAge#71] opened 2020-02-13 20:33 UTC
This is more for final polished product. Some UI effects would be to:
* Shake screen/text bubble if character is shouting
* Change font
* Creating better borders
* Figure out how people find the text based on playtesting

**Comment by jurcaua** [comment] 2020-03-09 13:41
Closing due to being a duplicate of #189

**Closed as completed by jurcaua** 2020-03-09 13:41 UTC
Labels: feature
